name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 0.9.11
homepage: https://github.com/surielb/chewie.git

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.9.1 <2.0.0"

dependencies:
  open_iconic_flutter: ">=0.3.0 <0.4.0"
  video_player:
    git:
      url: https://github.com/surielb/plugins.git
      path: packages/video_player/video_player
  #">=1.0.1 <1.1.0"
  wakelock: ^0.4.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
